Repository evrekadev/evreka-api-doc, pull requests merged in 2025-09, with the labels that each got.

#99 DEV-19812
  source/engagement/order/list.rst
Labels: Pending QA, Waiting CR

#106 Sprint/125
  source/changelog.rst
  source/conf.py
  source/engagement/contact/create.rst
  source/engagement/contact/update.rst
  source/engagement/order/list.rst
  source/engagement/service_point/index.rst
  source/engagement/service_point/update.rst
Labels: Release Package

#117 DEV-20040
  source/mrf/consignment/change-status.rst
  source/mrf/consignment/index.rst
  source/mrf/consignment/status-list.rst
Labels: Pending QA, Waiting CR, AI Review

#118 DEV-20041
  source/mrf/consignment/create.rst
  source/mrf/consignment/detail.rst
  source/mrf/consignment/index.rst
Labels: Pending QA, Waiting CR, AI Review

#111 DEV-18617: Outbound API - STG
  source/changelog.rst
  source/mrf/consignment/change-status.rst
  source/mrf/consignment/create.rst
  source/mrf/consignment/index.rst
  source/mrf/consignment/list.rst
  source/mrf/consignment/status-list.rst
  source/mrf/consignment/types-list.rst
  source/mrf/index.rst
Labels: Pending QA, Waiting CR

#109 E360-19922: Order Settings - Order Items Uom Field Sending
  source/engagement/order_settings/get.rst
Labels: Ready for Release
