Repository evrekadev/evreka-api-doc, pull requests merged in 2025-03, with the labels that each got.

#28 Feature 18151/create entity api
  source/engagement/entity/create.rst
  source/engagement/entity/index.rst
Labels: Ready for Release

#29 Feature/service point creation api
  source/engagement/case/create.rst
  source/engagement/order/create.rst
  source/engagement/service_point/create.rst
  source/engagement/service_point/dynamic_field_list.rst
  source/engagement/service_point/index.rst
  source/engagement/service_point/types.rst
Labels: Ready for Release

#30 DEV-18152
  source/engagement/entity/index.rst
  source/engagement/entity/types.rst
Labels: Ready for Release

#31 E360-18153: Entity Dynamic Field List API
  source/engagement/entity/dynamic_fields.rst
  source/engagement/entity/index.rst
Labels: Waiting CR

#39 Sprint/112
  source/engagement/case/create.rst
  source/engagement/entity/create.rst
  source/engagement/entity/dynamic_fields.rst
  source/engagement/entity/index.rst
  source/engagement/entity/types.rst
  source/engagement/index.rst
  source/engagement/order/create.rst
  source/engagement/order_asset_records/index.rst
  source/engagement/order_asset_records/list.rst
  source/engagement/order_item_records/index.rst
  source/engagement/order_item_records/list.rst
  source/engagement/service_point/create.rst
  source/engagement/service_point/dynamic_field_list.rst
  source/engagement/service_point/index.rst
  source/engagement/service_point/locations_list.rst
  source/engagement/service_point/types.rst
Labels: Ready for Release

#40 DEV-18147 order detail api
  source/engagement/order/detail.rst
  source/engagement/order/index.rst
Labels: Ready for Release

#41 DEV-18336 | announcement list documentation
  source/engagement/announcement/index.rst
  source/engagement/announcement/list.rst
  source/engagement/index.rst
Labels: Waiting CR

#43 DEV-18144 feature task api tests
  source/index.rst
  source/ops/base_url.rst
  source/ops/index.rst
  source/ops/task/detail.rst
  source/ops/task/index.rst
  source/ops/task/step-detail.rst
  source/ops/task/transitions.rst
Labels: Pending QA

#45 Sprint/113
  source/engagement/announcement/index.rst
  source/engagement/announcement/list.rst
  source/engagement/index.rst
  source/engagement/order/detail.rst
  source/engagement/order/index.rst
  source/index.rst
  source/ops/base_url.rst
  source/ops/index.rst
  source/ops/task/detail.rst
  source/ops/task/index.rst
  source/ops/task/step-detail.rst
  source/ops/task/transitions.rst
Labels: Ready for Release
